export enum DTOType {
    CALENDAR = "calendar",
    CALENDAR_ERA = "calendar_era",
    CALENDAR_MONTH = "calendar_month",
    CALENDAR_MOON = "calendar_moon",
    CALENDAR_MOON_PHASE = "calendar_moon_phase",
    CALENDAR_WEEK_DAY = "calendar_week_day",
    CHARACTER = "character",
    CURRENT_DATE = "current_date",
    DATA = "data",
    DATE = "date",
    NICKNAME = "nickname",
    PARTY = "party",
    PARTY_FUND = "party_fund",
    SENDING = "sending",
    SPECIAL_CHANNEL = "special_channel",
    USER = "user",
    WORLD = "world",

}