export const TYPES = {
    App: Symbol("App"),

    ClientID: Symbol("ClientID"),
    CryptKey: Symbol("CryptKey"),
    DatabaseUrl: Symbol("DatabaseUrl"),
    Issuer: Symbol("Issuer"),

    Authorization: Symbol("Authorization"),

    CharacterController: Symbol("CharacterController"),
    CalendarController: Symbol("CalendarController"),
    CalendarEraController: Symbol("CalendarEraController"),
    CalendarMonthController: Symbol("CalendarMonthController"),
    CalendarMoonController: Symbol("CalendarMoonController"),
    CalendarMoonPhaseController: Symbol("CalendarMoonPhaseController"),
    CalendarWeekDayController: Symbol("CalendarWeekDayController"),
    CurrentDateController: Symbol("CurrentDateController"),
    DateController: Symbol("DateController"),
    PartyController: Symbol("PartyController"),
    PartyFundController: Symbol("PartyFundController"),
    SendingController: Symbol("SendingController"),
    SpecialChannelController: Symbol("SpecialChannelController"),
    UserController: Symbol("UserController"),
    WorldController: Symbol("WorldController"),

    DatabaseService: Symbol("DatabaseService"),

    CalendarRoute: Symbol("CalendarRoute"),
    CharacterRoute: Symbol("CharacterRoute"),
    CurrentDateRoute: Symbol("CurrentDateRoute"),
    DateRoute: Symbol("DateRoute"),
    DiscordIDRoute: Symbol("DiscordIDRoute"),
    PartyRoute: Symbol("PartyRoute"),
    PartyFundRoute: Symbol("PartyFundRoute"),
    SendingRoute: Symbol("SendingRoute"),
    SpecialChannelRoute: Symbol("SpecialChannelRoute"),
    UserRoute: Symbol("UserRoute"),
    WorldRoute: Symbol("WorldRoute"),
};